apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7c3g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7c3g
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7c3g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7c3g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7c3g
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lvzb-tenant/rhtap-demo-app/hacbs-test-project-7c3g@sha256:429f1fe34e28806fd9c46a560f705e6dca3accd31a1a8772d835d9f6fb89dfa4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
